controller_list:
  - name: fake_group_arm_controller
    joints:
      - arm_shoulder_yaw_joint
      - arm_shoulder_pitch_joint
      - arm_elbow_pitch_joint
      - arm_wrist_pitch_joint
  - name: fake_group_gripper_controller
    joints:
      - arm_gripper_right_joint